org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false

# ✅ تنظیمات پروکسی برای دسترسی به مخازن گوگل
# پورت را با پورت واقعی VPN خود جایگزین کنید
# برای V2Ray/Xray معمولاً 10809 یا 10808
# برای SOCKS5 معمولاً 1080 یا 7890
systemProp.http.proxyHost=192.168.100.5
systemProp.http.proxyPort=4865
systemProp.https.proxyHost=192.168.100.5
systemProp.https.proxyPort=4865
systemProp.http.nonProxyHosts=192.168.100.5